const URL = import.meta.env.VITE_SERVER_URL;

export const API_ENDPOINTS = {
  API_URL: URL,
  signup: URL + "auth/signup",
  verificationEmail: URL + "verification/email",
  staemVerify: URL + "steam/verify",
  signin: URL + "auth/signin",
  steam_signin: URL + "auth/steam/signin",
  logout: URL + "auth/logout",
  recoveryPassword: URL + "recovery/password",
  accountRecovery: URL + "recovery/verify",
  refresh: URL + "auth/refresh",
  commentCreate: URL + "comment/create/",
  commentDelete: URL + "comment/",
  commentUpdate: URL + "comment/",
  comments: URL + "comments/",
  steamid: URL + "steam/",
  getSteamViewers: URL + "getViewers/",
  profile: URL + "profile",
  me: URL + "profile/me",
  createReport: URL + "createReport",
  getDemos: URL + "getDemos",
  postVerdict: URL + "postVerdict/",
  getMyVerdicts: URL + "getMyVerdicts",
  getMyReports: URL + "getMyReports",
  patchSocialLinks: URL + "social-links/update",
  getSocialLinks: URL + "social-links/get/",
  getMyNotifications: URL + "getMyNotifications",
  setViewedNotification: URL + "setViewedNotification",
  uploadImage: URL + "image/upload",
  addTrackingUser: URL + "tracking-users/addUser",
  deleteTrackingUser: URL + "tracking-users/deleteUser/",
  getTrackingUsers: URL + "tracking-users/getUsers",
  getCS2Stats: URL + "cs2stats/get/",
  getCS2AccountData: URL + "cs2/userdata",
};

export const S3 = {
  image: import.meta.env.VITE_S3_IMAGE_URL,
  medal: import.meta.env.VITE_S3_MEDAL_URL,
};
