const URL = import.meta.env.VITE_SERVER_URL;

export const API_ENDPOINTS = {
  API_URL: URL,
  signup: URL + "auth/signup",
  emailVerify: URL + "auth/emailVerify/",
  staemVerify: URL + "steam/verify",
  signin: URL + "auth/signin",
  logout: URL + "auth/logout",
  refresh: URL + "auth/refresh",
  commentCreate: URL + "comment/create/",
  commentDelete: URL + "comment/",
  commentUpdate: URL + "comment/",
  comments: URL + "comments/",
  steamid: URL + "steam/",
  getSteamViewers: URL + "getViewers/",
  profile: URL + "profile",
  me: URL + "profile/me",
  createReport: URL + "createReport",
  getDemos: URL + "getDemos",
  postVerdict: URL + "postVerdict/",
  getMyVerdicts: URL + "getMyVerdicts",
  getMyReports: URL + "getMyReports",
  patchSocialLinks: URL + "social-links/update",
};
